### Install BiocManager if not installed
if(!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
### Bioconductor packages
BiocManager::install("DESeq2")
BiocManager::install("apeglm")
BiocManager::install("msigdbr")
BiocManager::install("enrichplot")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("tidyverse, Force = True")

### CRAN packages
install.packages("ggplot2")
install.packages("EnhancedVolcano")
install.packages("pheatmap")
install.packages("RColorBrewer")
install.packages("gridExtra")
install.packages("dplyr")
install.packages("tidyverse")
install.packages("magrittr")

### Unpacking packages
library(DESeq2)
library(apeglm)
library(clusterProfiler)
library(msigdbr)
library(enrichplot)
library(org.Hs.eg.db)
library(ggplot2)
library(EnhancedVolcano)
library(pheatmap)
library(RColorBrewer)
library(gridExtra)
library(dplyr)
library(tidyverse)
library(magrittr)
install.packages("tidyverse")
library(tidyverse)


library(DESeq2)
library(apeglm)
library(clusterProfiler)
library(msigdbr)
library(enrichplot)
library(org.Hs.eg.db)
library(ggplot2)
library(EnhancedVolcano)
library(pheatmap)
library(RColorBrewer)
library(gridExtra)
library(dplyr)
library(tidyverse)
library(magrittr)